# Generated by Django 3.2.9 on 2021-11-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201206_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='seller_info',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
